# - name: 'gcr.io/cloud-builders/docker'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     echo "Here's a convenient pattern to use for embedding shell scripts in cloudbuild.yaml."
#     echo "This step only pushes an image if this build was triggered by a push to master."
#     [[ "$BRANCH_NAME" == "master" ]] && docker push gcr.io/$PROJECT_ID/image

steps:
  - id: "Install node_modules"
    name: "gcr.io/cloud-builders/yarn"
    args: ["install"]
  - id: "Yarn Version"
    name: "gcr.io/cloud-builders/yarn"
    args: ["--version"]
  - id: "Install Prisma globally"
    name: "gcr.io/cloud-builders/yarn"
    args: ["global", "add", "prisma"]
  - name: "ubuntu"
    args: ["source", "./scripts/get-env-staging.sh"]
  # - id: 'Lint'
  #   name: 'gcr.io/cloud-builders/yarn'
  #   args: ['run', 'lint']
  # - id: 'Test'
  #   name: 'gcr.io/cloud-builders/yarn'
  #   args: ['test']
  - id: "Generate app.yaml"
    name: "gcr.io/cloud-builders/nodejs"
    args: ["app.template.yaml", "app.yaml"]
  - id: "Build"
    name: "gcr.io/cloud-builders/yarn"
    args: ["build"]
  # - name: "gcr.io/cloud-builders/gcloud"
  #   dir: "frontend"
  #   args: ["app", "deploy"]

timeout: "300s"
