language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add prisma

script:
  - pushd prisma-services/continuous
  - export PRISMA_ENDPOINT="$PRISMA_SERVER/$PRISMA_SERVICE_NAME/$TRAVIS_PULL_REQUEST_BRANCH"
  - echo $PRISMA_ENDPOINT
  - prisma deploy
  - popd
# script:
#   - cd continuous
#   # parse henry.ymal to read prismaServer address
#   # parse prisma.yml to read app name
#   # read git branch
#   - export PRISMA_ENDPOINT=<henry:prismaServer>/my-app/<stage/branch>
#   # deploy schema
#   - prisma deploy
#   # create prisma-client (can also be hook of deploy script)
#   - prisma generate

#   # back to root project
#   - cd ..
#   # create GraphQL server
#   - yarn build
#   # deploy GraphQL server
#   - serverless deploy dist
