language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # install specific version of yarn, as the one provided by Travis does not
  # support pinning package versions yet (using "resolutions" property in
  # package.json)
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  # make prisma available
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add prisma

script:
  - pushd prisma-services/continuous
  # set PRISMA_ENDPOINT for "prisma deploy"
  - export PRISMA_ENDPOINT="$PRISMA_SERVER/$PRISMA_SERVICE_NAME/$TRAVIS_PULL_REQUEST_BRANCH"
  - prisma deploy
  - popd
  # prisma deployment has a hook which will generate an appropriate
  # prisma-client

  # deploy GraphQL server
  # we use the pr number for the stage, as
  #  - the AWS stage may only use a-zA-Z0-9
  #  - the AWS roleName must have 64 chars max
  - yarn deploy --stage $TRAVIS_PULL_REQUEST |tee serverless-deployment.log
  - export GRAPHQL_ENDPOINT="$(cat serverless-deployment.log | grep GET | sed s/\ *GET\ -\ *//g)"
  - echo $GRAPHQL_ENDPOINT
