language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add prisma

script:
  - pushd prisma-services/continuous
  # set PRISMA_ENDPOINT for "prisma deploy"
  - export PRISMA_ENDPOINT="$PRISMA_SERVER/$PRISMA_SERVICE_NAME/$TRAVIS_PULL_REQUEST_BRANCH"
  - prisma deploy
  - popd
  # prisma deployment has a hook which will generate an appropriate
  # prisma-client

  # deploy GraphQL server
  - yarn deploy
