language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # install specific version of yarn, as the one provided by Travis does not
  # support pinning package versions yet (using "resolutions" property in
  # package.json)
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  # make prisma available
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add prisma

script:
  - pushd prisma-services/continuous
  # set PRISMA_ENDPOINT for "prisma deploy"
  - export PRISMA_ENDPOINT="$PRISMA_SERVER/$PRISMA_SERVICE_NAME/$TRAVIS_PULL_REQUEST_BRANCH"
  - prisma deploy
  # generate manually as hook is not set up yet
  - prisma generate
  - popd
  # prisma deployment has a hook which will generate an appropriate
  # prisma-client

  # deploy GraphQL server
  - yarn deploy --stage branch1
