language: node_js

node_js:
  - "10"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # decrypt Google App Engine client secret
  - openssl aes-256-cbc -K $encrypted_fcdc1e9b32f5_key -iv $encrypted_fcdc1e9b32f5_iv
    -in gae-client-secret.json.enc -out gae-client-secret.json -d
  # install specific version of yarn, as the one provided by Travis does not
  # support pinning package versions yet (using "resolutions" property in
  # package.json)
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  # make prisma available
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add prisma

script:
  - pushd graphql-server/prisma-services/continuous
  # set PRISMA_ENDPOINT for "prisma deploy"
  - export PRISMA_ENDPOINT="$PRISMA_SERVER/$PRISMA_SERVICE_NAME/$TRAVIS_PULL_REQUEST_BRANCH"
  - prisma deploy
  - popd
  # prisma deployment has a hook which will generate an appropriate
  # prisma-client

  # deploy GraphQL server
  # we use the pr number for the stage, as
  #  - the AWS stage may only use a-zA-Z0-9
  #  - the AWS roleName must have 64 chars max
  - yarn gs:deploy --stage $TRAVIS_PULL_REQUEST |tee serverless-deployment.log
  - export GRAPHQL_ENDPOINT="$(cat serverless-deployment.log | grep GET | sed s/\ *GET\ -\ *//g)"
  - echo $GRAPHQL_ENDPOINT

# https://docs.travis-ci.com/user/deployment/google-app-engine/
deploy:
  provider: gae
  config: app.yaml
  # is decrypted by script in before_install
  keyfile: gae-client-secret.json
  # even though the project is contained in the gae-client-secret,
  # we need to specify it as gcloud will use the repo name otherwise
  project: henry-228416
  service: default
  # version: <i would like to use the branch name here>
  version: "$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER"
  # depends on whether this is production, staging or branch deployment
  no_promote: true
  # depends on whether this is production, staging or branch deployment
  no_stop_previous_version: true
  # not sure whether this is needed
  skip_cleanup: true
  # deploy from all branches
  on:
    all_branches: true
