language: node_js

# safelist
branches:
  only:
    - master

node_js:
  - "10"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # decrypt Google App Engine client secret
  - openssl aes-256-cbc -K $encrypted_fcdc1e9b32f5_key -iv $encrypted_fcdc1e9b32f5_iv
    -in keys/gae-client-secret.json.enc -out keys/gae-client-secret.json -d
  # install specific version of yarn, as the one provided by Travis does not
  # support pinning package versions yet (using "resolutions" property in
  # package.json)
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  # make prisma available
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add prisma

script: scripts/build.sh

# https://docs.travis-ci.com/user/deployment/google-app-engine/
deploy:
  - provider: gae
    config: frontend/app.yaml
    # is decrypted by script in before_install
    keyfile: keys/gae-client-secret.json
    # even though the project is contained in the gae-client-secret,
    # we need to specify it as gcloud will use the repo name otherwise
    project: henry-228416
    # Ein Name kann Zahlen, Buchstaben und Bindestriche enthalten.
    # Er darf höchstens 63 Zeichen lang sein und darf nicht mit einem Bindestrich
    # beginnen oder enden. Wählen Sie für jeden Dienst und jede Version einen
    # eindeutigen Namen. Verwenden Sie nicht identische Namen für Dienste und
    # Versionen.
    version: $APP_RELEASE_NAME
    # depends on whether this is production, staging or branch deployment
    no_promote: true
    # depends on whether this is production, staging or branch deployment
    no_stop_previous_version: true
    # not sure whether this is needed
    skip_cleanup: true
    # deploy from all branches
    on:
      all_branches: true
  - provider: gae
    config: graphql-server/app.yaml
    # is decrypted by script in before_install
    keyfile: keys/gae-client-secret.json
    # even though the project is contained in the gae-client-secret,
    # we need to specify it as gcloud will use the repo name otherwise
    project: henry-228416
    # Ein Name kann Zahlen, Buchstaben und Bindestriche enthalten.
    # Er darf höchstens 63 Zeichen lang sein und darf nicht mit einem Bindestrich
    # beginnen oder enden. Wählen Sie für jeden Dienst und jede Version einen
    # eindeutigen Namen. Verwenden Sie nicht identische Namen für Dienste und
    # Versionen.
    version: $APP_RELEASE_NAME
    # depends on whether this is production, staging or branch deployment
    no_promote: true
    # depends on whether this is production, staging or branch deployment
    no_stop_previous_version: true
    # not sure whether this is needed
    skip_cleanup: true
    # deploy from all branches
    on:
      all_branches: true

after_script:
  # log for sanity
  - echo $PRISMA_ENDPOINT # used by "prisma deploy" & "prisma generate"
  - echo $FRONTEND_ENDPOINT
  - echo $GRAPHQL_ENDPOINT
