# Workflow tips
# https://serverless.com/framework/docs/providers/aws/guide/workflow/#using-stages
service: ci-travis-example

plugins:
  - serverless-offline

# only necessary for serverless platform, and optional
app: henry-example-app
tenant: dferber90

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    PRISMA_ENDPOINT: ${env:PRISMA_ENDPOINT}

functions:
  graphql:
    handler: handler.server
    events:
      - http:
          path: /
          method: post
          cors: true
  playground:
    handler: handler.playground
    events:
      - http:
          path: /
          method: get
          cors: true
